version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        depends_on:
                - db
    db:
        image: mysql
        command: --default-authentication-plugin=caching_sha2_password # change from caching_sha2_password
        environment:
            MYSQL_ROOT_PASSWORD: Ip38w#*5tA%hwJLy
            MYSQL_DATABASE: comp3335
            MYSQL_USER: user
            MYSQL_PASSWORD: 2d4h#AS
        ports: 
            - "33306:3306"        
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
    mysqlexporter:
        image: prom/mysqld-exporter
        ports:
            - "9104:9104"
        environment:
            - DATA_SOURCE_NAME=root:Ip38w#*5tA%hwJLy@(db:3306)/comp3335
    grafana:
        image: grafana/grafana
        ports:
            -  "9876:3000"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            PMA_HOST: 'db'
            PMA_PORT: '3306'
            PMA_USER: 'root'
            PMA_PASSWORD: "Ip38w#*5tA%hwJLy"
        depends_on:
            - db
            
volumes:
    persistent:
